import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import CustomLink from "./components/CustomLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="py-4 border-b border-gray-600">
          <ul className="flex gap-5">
            <li>
              <CustomLink path="/">Home</CustomLink>
            </li>
            <CustomLink path="/dashboard/analytics">About</CustomLink>
            <li>
              <CustomLink path="/dashboard/settings">Contact us</CustomLink>
            </li>
            <li>Footer</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
